"""create books table

Revision ID: 8e93b75a9518
Revises:
Create Date: 2019-12-23 15:57:43.428553

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '8e93b75a9518'
down_revision = None
branch_labels = None
depends_on = None

FICTION =  u'0'
NONFICTIONAL = u'1'
EDUCATIONAL = u'2'

BookTypes = [
  (FICTION, u'nonfiction'),
  (NONFICTIONAL, u'fiction'),
  (EDUCATIONAL, u'educational')
  ]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('book_type', sqlalchemy_utils.types.choice.ChoiceType(BookTypes), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
